### ISSUE TITLE
Fehler unter PHP 7.2

### ISSUE THREAD

**Issue by k-webdesign** [christianbarkowsky/tabcontrol#30]
Unter PHP 7.2 kommt: 

Warning: count(): Parameter must be an array or an object that implements Countable in system/modules/tabcontrol/elements/ContentTabControl.php on line 41
#0 [internal function]: __error(2, 'count(): Parame...', '/kunden/***...', 41, Array)
#1 system/modules/tabcontrol/elements/ContentTabControl.php(41): count('')
#2 system/modules/core/elements/ContentElement.php(265): Contao\ContentTabControl->compile()
#3 system/modules/core/library/Contao/Controller.php(484): Contao\ContentElement->generate()
#4 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#5 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#6 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#7 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#8 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), true, false, 'main')
#9 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#10 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#11 index.php(20): Contao\FrontendIndex->run()
#12 {main}

Warning: Cannot modify header information - headers already sent by (output started at /kunden/***/webseiten/contao-messeabteilung-2016/system/helper/functions.php:65) in system/modules/core/library/Contao/Template.php on line 294
#0 [internal function]: __error(2, 'Cannot modify h...', '/kunden/***...', 294, Array)
#1 system/modules/core/library/Contao/Template.php(294): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/FrontendTemplate.php(121): Contao\Template->output()
#3 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#4 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#5 index.php(20): Contao\FrontendIndex->run()
#6 {main}

Warning: Cannot modify header information - headers already sent by (output started at /kunden/***/webseiten/contao-messeabteilung-2016/system/helper/functions.php:65) in system/modules/core/library/Contao/Template.php on line 295
#0 [internal function]: __error(2, 'Cannot modify h...', '/kunden/***...', 295, Array)
#1 system/modules/core/library/Contao/Template.php(295): header('Content-Type: t...')
#2 system/modules/core/classes/FrontendTemplate.php(121): Contao\Template->output()
#3 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#4 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#5 index.php(20): Contao\FrontendIndex->run()
#6 {main}

Mit 7.1 geht es.

**Comment by crckmc** [comment]
Hallo,

bei mir ist es genau der gleiche Fehler bei PHP > 7.1 mit 7.1 geht es.
